// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8lhj8_i_-EJJGlbbRBUZhUdZMFaJh14',
    appId: '1:1092241176622:android:09b9e3340b397fba4bc7bf',
    messagingSenderId: '1092241176622',
    projectId: 'bobprep-47fca',
    storageBucket: 'bobprep-47fca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCml808LRPZPA27IaAw2yegQsXD5mXD7Yg',
    appId: '1:1092241176622:ios:47099674aa24badf4bc7bf',
    messagingSenderId: '1092241176622',
    projectId: 'bobprep-47fca',
    storageBucket: 'bobprep-47fca.appspot.com',
    androidClientId: '1092241176622-cc4d8l0bt1j8m86ip56me2opud2ag9qp.apps.googleusercontent.com',
    iosClientId: '1092241176622-7necta29idnkpdt93rloqkal9n3u6qce.apps.googleusercontent.com',
    iosBundleId: 'com.infixlms.app',
  );
}
